{"time":"2025-10-06T11:00:01.4059732+05:00","level":"INFO","msg":"ðŸ”§ Logger initialized"}
{"time":"2025-10-06T11:00:01.4484834+05:00","level":"INFO","msg":"Config file loaded","path":"C:\\Users\\ulana\\GolandProjects\\RealtimeService\\config\\config.yaml"}
{"time":"2025-10-06T11:00:01.4490173+05:00","level":"INFO","msg":"Config loaded","app_host":"localhost","app_port":"8081","kafka_topic":"raw-address","kafka_group":"raw-id","kafka_brokers":["192.168.1.220:9092"],"read_timeout":10000000000,"write_timeout":10000000000}
{"time":"2025-10-06T11:00:01.4490173+05:00","level":"INFO","msg":"Starting Kafka consumer","object":"stream","layer":"kafka_consumer","topic":"raw-address","group":"raw-id","brokers":["192.168.1.220:9092"]}
{"time":"2025-10-06T11:00:01.4585363+05:00","level":"INFO","msg":"âœ… Kafka consumer started"}
{"time":"2025-10-06T11:00:01.4590845+05:00","level":"INFO","msg":"ðŸš€ WebSocket server starting","addr":"localhost:8081"}
{"time":"2025-10-06T11:00:11.6715548+05:00","level":"INFO","msg":"ValidateToken called","object":"connection","layer":"AuthRepository","token":"anything"}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"INFO","msg":"WebSocket connection established","object":"connection","layer":"WShandler","user_id":1}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"INFO","msg":"HandleConnection started","object":"connection","layer":"UseCase","user_id":1}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"INFO","msg":"GetUserUnits called","object":"connection","layer":"UnitRepository","user_id":1}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"DEBUG","msg":"Returning unit IDs","object":"connection","layer":"UnitRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"DEBUG","msg":"Subscribing to units","object":"connection","layer":"UseCase","user_id":1,"unit_ids":[586,102,103]}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"INFO","msg":"Subscribed connection","object":"server","layer":"Hub","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"INFO","msg":"GetLastData called","object":"connection","layer":"RedisRepository","unit_count":3}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"DEBUG","msg":"Fetching last data for unitIDs","object":"connection","layer":"RedisRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"DEBUG","msg":"Returning mock result","object":"connection","layer":"RedisRepository","result_count":3}
{"time":"2025-10-06T11:00:11.6725559+05:00","level":"DEBUG","msg":"Sent last data to client","object":"connection","layer":"UseCase","count":3}
{"time":"2025-10-06T11:07:00.0950799+05:00","level":"INFO","msg":"Connection closed","object":"connection","layer":"UseCase","user_id":1,"error":"websocket: close 1000 (normal)"}
{"time":"2025-10-06T11:07:00.0950799+05:00","level":"INFO","msg":"Unsubscribed connection","object":"server","layer":"Hub","removed_from_units":3}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"ValidateToken called","object":"connection","layer":"AuthRepository","token":"anything"}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"WebSocket connection established","object":"connection","layer":"WShandler","user_id":1}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"HandleConnection started","object":"connection","layer":"UseCase","user_id":1}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"GetUserUnits called","object":"connection","layer":"UnitRepository","user_id":1}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"DEBUG","msg":"Returning unit IDs","object":"connection","layer":"UnitRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"DEBUG","msg":"Subscribing to units","object":"connection","layer":"UseCase","user_id":1,"unit_ids":[586,102,103]}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"Subscribed connection","object":"server","layer":"Hub","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"INFO","msg":"GetLastData called","object":"connection","layer":"RedisRepository","unit_count":3}
{"time":"2025-10-06T11:07:03.5717459+05:00","level":"DEBUG","msg":"Fetching last data for unitIDs","object":"connection","layer":"RedisRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:07:03.5722617+05:00","level":"DEBUG","msg":"Returning mock result","object":"connection","layer":"RedisRepository","result_count":3}
{"time":"2025-10-06T11:07:03.5723361+05:00","level":"DEBUG","msg":"Sent last data to client","object":"connection","layer":"UseCase","count":3}
{"time":"2025-10-06T11:07:07.868425+05:00","level":"INFO","msg":"ðŸ›‘ Shutdown signal received"}
{"time":"2025-10-06T11:07:07.868425+05:00","level":"INFO","msg":"âœ… Server gracefully stopped"}
{"time":"2025-10-06T11:08:50.7909525+05:00","level":"INFO","msg":"ðŸ”§ Logger initialized"}
{"time":"2025-10-06T11:08:50.8315071+05:00","level":"INFO","msg":"Config file loaded","path":"C:\\Users\\ulana\\GolandProjects\\RealtimeService\\config\\config.yaml"}
{"time":"2025-10-06T11:08:50.8315071+05:00","level":"INFO","msg":"Config loaded","app_host":"localhost","app_port":"8081","kafka_topic":"raw-address","kafka_group":"raw-id","kafka_brokers":["192.168.1.220:9092"],"read_timeout":10000000000,"write_timeout":10000000000}
{"time":"2025-10-06T11:08:50.8320276+05:00","level":"INFO","msg":"Starting Kafka consumer","object":"stream","layer":"kafka_consumer","topic":"raw-address","group":"raw-id","brokers":["192.168.1.220:9092"]}
{"time":"2025-10-06T11:08:50.8466561+05:00","level":"INFO","msg":"âœ… Kafka consumer started"}
{"time":"2025-10-06T11:08:50.8466561+05:00","level":"INFO","msg":"ðŸš€ WebSocket server starting","addr":"localhost:8081"}
{"time":"2025-10-06T11:08:52.0932045+05:00","level":"INFO","msg":"ValidateToken called","object":"connection","layer":"AuthRepository","token":"anything"}
{"time":"2025-10-06T11:08:52.093754+05:00","level":"INFO","msg":"WebSocket connection established","object":"connection","layer":"WShandler","user_id":1}
{"time":"2025-10-06T11:08:52.093754+05:00","level":"INFO","msg":"HandleConnection started","object":"connection","layer":"UseCase","user_id":1}
{"time":"2025-10-06T11:08:52.0942638+05:00","level":"INFO","msg":"GetUserUnits called","object":"connection","layer":"UnitRepository","user_id":1}
{"time":"2025-10-06T11:08:52.0942638+05:00","level":"DEBUG","msg":"Returning unit IDs","object":"connection","layer":"UnitRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"DEBUG","msg":"Subscribing to units","object":"connection","layer":"UseCase","user_id":1,"unit_ids":[586,102,103]}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"INFO","msg":"Subscribed connection","object":"server","layer":"Hub","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"INFO","msg":"GetLastData called","object":"connection","layer":"RedisRepository","unit_count":3}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"DEBUG","msg":"Fetching last data for unitIDs","object":"connection","layer":"RedisRepository","unit_ids":[586,102,103]}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"DEBUG","msg":"Returning mock result","object":"connection","layer":"RedisRepository","result_count":3}
{"time":"2025-10-06T11:08:52.0942867+05:00","level":"DEBUG","msg":"Sent last data to client","object":"connection","layer":"UseCase","count":3}
{"time":"2025-10-06T11:08:54.4193084+05:00","level":"INFO","msg":"Connection closed","object":"connection","layer":"UseCase","user_id":1,"error":"websocket: close 1000 (normal)"}
{"time":"2025-10-06T11:08:54.4193084+05:00","level":"INFO","msg":"Unsubscribed connection","object":"server","layer":"Hub","removed_from_units":3}
{"time":"2025-10-06T11:08:54.4193084+05:00","level":"INFO","msg":"HTTP request","method":"GET","path":"/ws","status":200,"latency":2326103900,"client_ip":"127.0.0.1"}
{"time":"2025-10-06T12:33:07.8578901+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:34:32.7775712+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:35:57.6751424+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:37:22.5991502+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:38:47.5165552+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:40:12.4040106+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:41:37.3169109+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:43:02.2738044+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:44:27.1525144+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:45:52.0863698+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:47:16.9707766+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:48:41.9256019+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:50:06.8541801+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:51:31.7730463+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:52:56.7004824+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:54:21.6197248+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:55:46.518162+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:57:11.4256225+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T12:58:36.3233548+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:00:01.2317513+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:01:26.1019647+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:02:51.0103026+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:04:15.9575399+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:05:40.8551303+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:07:05.7238255+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:08:30.6298066+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:09:55.5495445+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:11:20.4837007+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:12:45.3950821+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:14:10.2974689+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:15:35.2171632+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:17:00.1174634+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:18:25.028904+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:19:49.905231+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:21:14.8091098+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:22:39.7135841+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:24:04.6212852+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:25:29.5290975+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:26:54.4166402+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:28:19.298603+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:29:44.1804724+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:31:09.1114959+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:32:33.995347+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:33:58.8711857+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:35:23.7935471+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:36:48.7109036+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:38:13.6109408+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:39:38.4800407+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:41:03.3994217+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:42:28.3118119+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:43:53.191109+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:45:18.1029593+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:46:43.0182263+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:48:07.9494022+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:49:32.8496858+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:50:57.7379432+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:52:22.6656258+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:53:47.5870367+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:55:12.5010949+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:56:37.4277978+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:58:02.3370777+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T13:59:27.2477593+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:00:52.1139605+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:02:17.0250494+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:03:41.9562423+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:05:06.8655604+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:06:31.7417021+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:07:56.6658031+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:09:21.5809846+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:10:46.5147657+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:12:11.4474148+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:13:36.3798996+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:15:01.2815836+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:16:26.164336+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:17:51.0342521+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:19:15.8980416+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:20:40.8377048+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:22:05.7358254+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:23:30.6716412+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:24:55.6160431+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:26:20.5027993+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:27:45.3848318+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:29:10.2626494+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:30:35.1710196+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:32:00.0958543+05:00","level":"ERROR","msg":"Kafka consume error","object":"stream","layer":"kafka_consumer","error":"kafka: client has run out of available brokers to talk to: dial tcp 192.168.1.220:9092: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-10-06T14:32:27.1035696+05:00","level":"INFO","msg":"ðŸ›‘ Shutdown signal received"}
{"time":"2025-10-06T14:32:27.1041107+05:00","level":"INFO","msg":"âœ… Server gracefully stopped"}
{"time":"2025-10-06T14:39:48.0765747+05:00","level":"INFO","msg":"Logger initialized"}
{"time":"2025-10-06T14:39:48.1159731+05:00","level":"INFO","msg":"Config file loaded","path":"C:\\Users\\ulana\\GolandProjects\\RealtimeService\\config\\config.yaml"}
{"time":"2025-10-06T14:39:48.1159731+05:00","level":"INFO","msg":"Config loaded","app_host":"localhost","app_port":"8081","kafka_topic":"raw-address","kafka_group":"raw-id","kafka_brokers":["192.168.1.220:9092"],"read_timeout":10000000000,"write_timeout":10000000000}
{"time":"2025-10-06T14:39:48.1159731+05:00","level":"INFO","msg":"Starting Kafka consumer","object":"stream","layer":"kafka_consumer","topic":"raw-address","group":"raw-id","brokers":["192.168.1.220:9092"]}
{"time":"2025-10-06T14:39:48.1409406+05:00","level":"INFO","msg":"Kafka consumer started"}
{"time":"2025-10-06T14:39:48.1415005+05:00","level":"INFO","msg":"WebSocket server starting","addr":"localhost:8081"}
{"time":"2025-10-06T14:39:48.1415005+05:00","level":"INFO","msg":"pprof available","addr":":6060"}
{"time":"2025-10-06T17:58:15.46607+05:00","level":"INFO","msg":"Shutdown signal received"}
{"time":"2025-10-06T17:58:15.46607+05:00","level":"INFO","msg":"Server gracefully stopped"}
